#version: '3.1'
#
#services:
#  db:
#    image: mysql:8.3
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'inventory'
#      MYSQL_ROOT_PASSWORD: '1234'
#    ports:
#      - '3306:3306'
#    volumes:
#      - ./db_data:/var/lib/mysql