name: Merge

on:
  push:
    branches:
      - main

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -XX:MaxMetaspaceSize=512m' -Dorg.gradle.parallel=true"
    steps: # action or script to run
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 커밋 기록을 가져옴
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Run test
        run: |
          ./gradlew -p "practices/inventory" test
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: test-and-analyze
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployed!"
