name: Merge

on:
  push:
    paths:
      - "inventory-system-test/**"
    branches:
      - main

jobs:
  inventory-test-and-analyze:
    name: Inventory Test and Analyze
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Xmx2g -XX:MaxMetaspaceSize=512m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
    steps: # action or script to run
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 커밋 기록을 가져옴
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Run test and jacoco
        run: |
          cd inventory-system-test
          ./gradlew -p "practices/inventory" test jacocoTestReport
  inventory-deploy:
    name: Inventory Deploy
    runs-on: ubuntu-22.04
    needs: inventory-test-and-analyze
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Deployed!"
